### ISSUE TITLE
[Feature]: `add_file` functions for development

### ISSUE THREAD

**Issue by DavidJesse21** [Appsilon/rhino#237] opened 2022-04-14 11:45 UTC
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Hi,
I have just discovered this package, have not tried it out yet, but it looks very promising!
I've been working on a very similar project, which I have called [`{box.shiny}`](https://github.com/DavidJesse21/box.shiny).
It was inspired by the golem package but aims to make use of box modules just like your package.
I was wondering, if you were thinking about adding `add_` functions as well like `add_module()` or `add_sass()`, that create the corresponding files with a template instead of manually adding them?

### Problem

`add_` functions could make use of some predefined templates, e.g. for shiny modules:

```r
box::use(
  ...
)

#' @export
ui = function() ...

#' @export
server = function() ...
```

That way you don't need to copy and paste some base code all the time.

### Proposed Solution

For files that need no initial customisation at all you could simply add the templates in the `inst` folder of this package.
For files that might need more customisation you can write a function that creates an empty file and writes the code/text to it like so: https://github.com/DavidJesse21/box.shiny/blob/main/R/add_modules.R

### Alternatives Considered

No

**Comment by kamilzyla** [comment] 2022-05-30 06:46
Duplicate of #103.

**Closed by kamilzyla** 2022-05-30 06:46 UTC
