### ISSUE TITLE
`rhino::test_e2e()` gets stuck on macOS

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/rhino#298] opened 2022-07-04 10:00 UTC
Originally reported [here](https://appsilon.slack.com/archives/C030THRK1QV/p1656688614770159) by @Gotfrid. When running `rhino::test_e2e()` the Shiny app is launched, but the tests are not run and the command does not exit by itself - only the "listening on…" message can be seen in the console.

### Diagnostics
```
Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
R version 4.1.2 (2021-11-01)
rhino: 1.0.0
node: v17.5.0
yarn: 1.22.17
```

### Workaround
1. Install `concurrently` via `cd ./.rhino/node && npm i concurrently --save-dev`
2. Change `test-e2e npm` script to:
    1. `"concurrently --raw --kill-others --success \"first\" \"npm run run-app\" \"npm run run-cypress\""`
    2. or shorter `"concurrently -rks \"first\" \"npm run run-app\" \"npm run run-cypress\""`

This can be used as a basis for a full solution, but we'll need to:
1. Use `yarn` instead of `npm` (unless we implement #104 first).
2. Test this on all platforms (Linux, macOS, Windows).
3. Test whether it works when the app takes a lot of time to launch (`test-server-and-run` waits for the server to be up and running before testing; `concurrently` might not do that).

**Comment by Leszek-Sieminski** [comment] 2022-12-04 10:16
Cannot reproduce this issue anymore, it doesn't appear. Closing

**Closed by Leszek-Sieminski** 2022-12-04 10:16 UTC
Labels: type: bug, status: ready
